[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stripe = { version = "0.26.0", features = ["runtime-tokio-hyper"] }
axum = "0.7.2"
axum-extra = { version = "0.9.0", features = ["cookie-private"] }
axum-macros = "0.4.0"
bcrypt = "0.15.0"
http = "1.0.0"
lettre = "0.11.2"
rand = "0.8.5"
reqwest = "0.11.16"
serde = { version = "1.0.160", features = ["derive"] }
shuttle-axum = "0.35.0"
shuttle-runtime = "0.35.0"
shuttle-secrets = "0.35.0"
shuttle-shared-db = { version = "0.35.0", features = ["postgres"] }
shuttle-static-folder = "0.28.0"
sqlx = { version = "0.7.3", features = ["runtime-tokio-native-tls", "postgres", "time"] }
time = { version = "0.3.20", features = ["serde"] }
tokio = "1.27.0"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors", "fs"] }
